const country_codes = [
  {
    Code: 'af',
    Name: 'Afghanistan',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'al',
    Name: 'Albania',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ag',
    Name: 'Algeria',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'an',
    Name: 'Andorra',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ao',
    Name: 'Angola',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ac',
    Name: 'Antigua and Barbuda',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ar',
    Name: 'Argentina',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'am',
    Name: 'Armenia',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'as',
    Name: 'Australia',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'au',
    Name: 'Austria',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'aj',
    Name: 'Azerbaijan',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'bf',
    Name: 'Bahamas, The',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ba',
    Name: 'Bahrain',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'bg',
    Name: 'Bangladesh',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'bb',
    Name: 'Barbados',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'bo',
    Name: 'Belarus',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'be',
    Name: 'Belgium',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'bh',
    Name: 'Belize',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'bn',
    Name: 'Benin',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'bt',
    Name: 'Bhutan',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'bl',
    Name: 'Bolivia',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'bk',
    Name: 'Bosnia and Herzegovina',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'bc',
    Name: 'Botswana',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'br',
    Name: 'Brazil',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'bx',
    Name: 'Brunei',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'bu',
    Name: 'Bulgaria',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'uv',
    Name: 'Burkina Faso',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'bm',
    Name: 'Burma',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'by',
    Name: 'Burundi',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'cb',
    Name: 'Cambodia',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'cm',
    Name: 'Cameroon',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ca',
    Name: 'Canada',
    Category: 'Countries',
    Region: 'North America',
  },
  {
    Code: 'cv',
    Name: 'Cabo Verde',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ct',
    Name: 'Central African Republic',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'cd',
    Name: 'Chad',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ci',
    Name: 'Chile',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'ch',
    Name: 'China',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'co',
    Name: 'Colombia',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'cn',
    Name: 'Comoros',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'cg',
    Name: 'Congo, Democratic Republic of the',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'cf',
    Name: 'Congo, Republic of the',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'cs',
    Name: 'Costa Rica',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'iv',
    Name: "Cote d'Ivoire",
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'hr',
    Name: 'Croatia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'cu',
    Name: 'Cuba',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'cy',
    Name: 'Cyprus',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ez',
    Name: 'Czechia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'da',
    Name: 'Denmark',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'dj',
    Name: 'Djibouti',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'do',
    Name: 'Dominica',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'dr',
    Name: 'Dominican Republic',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ec',
    Name: 'Ecuador',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'eg',
    Name: 'Egypt',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'es',
    Name: 'El Salvador',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ek',
    Name: 'Equatorial Guinea',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'er',
    Name: 'Eritrea',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'en',
    Name: 'Estonia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'et',
    Name: 'Ethiopia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'fj',
    Name: 'Fiji',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'fi',
    Name: 'Finland',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'fr',
    Name: 'France',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'gb',
    Name: 'Gabon',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ga',
    Name: 'Gambia, The',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'gg',
    Name: 'Georgia',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'gm',
    Name: 'Germany',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'gh',
    Name: 'Ghana',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'gr',
    Name: 'Greece',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'gj',
    Name: 'Grenada',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'gt',
    Name: 'Guatemala',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'gv',
    Name: 'Guinea',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'pu',
    Name: 'Guinea-Bissau',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'gy',
    Name: 'Guyana',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'ha',
    Name: 'Haiti',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ho',
    Name: 'Honduras',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'hu',
    Name: 'Hungary',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ic',
    Name: 'Iceland',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'in',
    Name: 'India',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'id',
    Name: 'Indonesia',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'ir',
    Name: 'Iran',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'iz',
    Name: 'Iraq',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'ei',
    Name: 'Ireland',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'is',
    Name: 'Israel',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'it',
    Name: 'Italy',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'jm',
    Name: 'Jamaica',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ja',
    Name: 'Japan',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'jo',
    Name: 'Jordan',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'kz',
    Name: 'Kazakhstan',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'ke',
    Name: 'Kenya',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'kr',
    Name: 'Kiribati',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'kn',
    Name: 'Korea, North',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'ks',
    Name: 'Korea, South',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'kv',
    Name: 'Kosovo',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ku',
    Name: 'Kuwait',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'kg',
    Name: 'Kyrgyzstan',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'la',
    Name: 'Laos',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'lg',
    Name: 'Latvia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'le',
    Name: 'Lebanon',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'lt',
    Name: 'Lesotho',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'li',
    Name: 'Liberia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ly',
    Name: 'Libya',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ls',
    Name: 'Liechtenstein',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'lh',
    Name: 'Lithuania',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'lu',
    Name: 'Luxembourg',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'mk',
    Name: 'North Macedonia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ma',
    Name: 'Madagascar',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'mi',
    Name: 'Malawi',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'my',
    Name: 'Malaysia',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'mv',
    Name: 'Maldives',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'ml',
    Name: 'Mali',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'mt',
    Name: 'Malta',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'rm',
    Name: 'Marshall Islands',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'mr',
    Name: 'Mauritania',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'mp',
    Name: 'Mauritius',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'mx',
    Name: 'Mexico',
    Category: 'Countries',
    Region: 'North America',
  },
  {
    Code: 'fm',
    Name: 'Micronesia, Federated States of',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'md',
    Name: 'Moldova',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'mn',
    Name: 'Monaco',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'mg',
    Name: 'Mongolia',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'mj',
    Name: 'Montenegro',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'mo',
    Name: 'Morocco',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'mz',
    Name: 'Mozambique',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'wa',
    Name: 'Namibia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'nr',
    Name: 'Nauru',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'np',
    Name: 'Nepal',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'nl',
    Name: 'Netherlands',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'nz',
    Name: 'New Zealand',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'nu',
    Name: 'Nicaragua',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ng',
    Name: 'Niger',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ni',
    Name: 'Nigeria',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'no',
    Name: 'Norway',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'mu',
    Name: 'Oman',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'pk',
    Name: 'Pakistan',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'ps',
    Name: 'Palau',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'pm',
    Name: 'Panama',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'pp',
    Name: 'Papua New Guinea',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'pa',
    Name: 'Paraguay',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'pe',
    Name: 'Peru',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'rp',
    Name: 'Philippines',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'pl',
    Name: 'Poland',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'po',
    Name: 'Portugal',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'qa',
    Name: 'Qatar',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'ro',
    Name: 'Romania',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'rs',
    Name: 'Russia',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'rw',
    Name: 'Rwanda',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sc',
    Name: 'Saint Kitts and Nevis',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'st',
    Name: 'Saint Lucia',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'vc',
    Name: 'Saint Vincent and the Grenadines',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ws',
    Name: 'Samoa',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'sm',
    Name: 'San Marino',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'tp',
    Name: 'Sao Tome and Principe',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sa',
    Name: 'Saudi Arabia',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'sg',
    Name: 'Senegal',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ri',
    Name: 'Serbia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'se',
    Name: 'Seychelles',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sl',
    Name: 'Sierra Leone',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sn',
    Name: 'Singapore',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'lo',
    Name: 'Slovakia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'si',
    Name: 'Slovenia',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'bp',
    Name: 'Solomon Islands',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'so',
    Name: 'Somalia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sf',
    Name: 'South Africa',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'od',
    Name: 'South Sudan',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sp',
    Name: 'Spain',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ce',
    Name: 'Sri Lanka',
    Category: 'Countries',
    Region: 'South Asia',
  },
  {
    Code: 'su',
    Name: 'Sudan',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'ns',
    Name: 'Suriname',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'wz',
    Name: 'Eswatini',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'sw',
    Name: 'Sweden',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'sz',
    Name: 'Switzerland',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'sy',
    Name: 'Syria',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'ti',
    Name: 'Tajikistan',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'tz',
    Name: 'Tanzania',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'th',
    Name: 'Thailand',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'tt',
    Name: 'Timor-Leste',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'to',
    Name: 'Togo',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'tn',
    Name: 'Tonga',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'td',
    Name: 'Trinidad and Tobago',
    Category: 'Countries',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'ts',
    Name: 'Tunisia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'tu',
    Name: 'Turkey',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'tx',
    Name: 'Turkmenistan',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'tv',
    Name: 'Tuvalu',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'ug',
    Name: 'Uganda',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'up',
    Name: 'Ukraine',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'ae',
    Name: 'United Arab Emirates',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'uk',
    Name: 'United Kingdom',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 'us',
    Name: 'United States',
    Category: 'Countries',
    Region: 'North America',
  },
  {
    Code: 'uy',
    Name: 'Uruguay',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'uz',
    Name: 'Uzbekistan',
    Category: 'Countries',
    Region: 'Central Asia',
  },
  {
    Code: 'nh',
    Name: 'Vanuatu',
    Category: 'Countries',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'vt',
    Name: 'Holy See (Vatican City)',
    Category: 'Countries',
    Region: 'Europe',
  },
  {
    Code: 've',
    Name: 'Venezuela',
    Category: 'Countries',
    Region: 'South America',
  },
  {
    Code: 'vm',
    Name: 'Vietnam',
    Category: 'Countries',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'ym',
    Name: 'Yemen',
    Category: 'Countries',
    Region: 'Middle East',
  },
  {
    Code: 'za',
    Name: 'Zambia',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'zi',
    Name: 'Zimbabwe',
    Category: 'Countries',
    Region: 'Africa',
  },
  {
    Code: 'tw',
    Name: 'Taiwan',
    Category: 'Other',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'ee',
    Name: 'European Union',
    Category: 'Other',
    Region: 'Europe',
  },
  {
    Code: 'at',
    Name: 'Ashmore and Cartier Islands',
    Category: 'Dependencies (Australia)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'kt',
    Name: 'Christmas Island',
    Category: 'Dependencies (Australia)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'ck',
    Name: 'Cocos (Keeling) Islands',
    Category: 'Dependencies (Australia)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'cr',
    Name: 'Coral Sea Islands',
    Category: 'Dependencies (Australia)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'hm',
    Name: 'Heard Island and McDonald Islands',
    Category: 'Dependencies (Australia)',
    Region: 'Antarctica',
  },
  {
    Code: 'nf',
    Name: 'Norfolk Island',
    Category: 'Dependencies (Australia)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'hk',
    Name: 'Hong Kong',
    Category: 'Dependencies (China)',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'mc',
    Name: 'Macau',
    Category: 'Dependencies (China)',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'fo',
    Name: 'Faroe Islands',
    Category: 'Dependencies (Denmark)',
    Region: 'Europe',
  },
  {
    Code: 'gl',
    Name: 'Greenland',
    Category: 'Dependencies (Denmark)',
    Region: 'North America',
  },
  {
    Code: 'ip',
    Name: 'Clipperton Island',
    Category: 'Dependencies (France)',
    Region: 'North America',
  },
  {
    Code: 'fp',
    Name: 'French Polynesia',
    Category: 'Dependencies (France)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'fs',
    Name: 'French Southern and Antarctic Lands',
    Category: 'Dependencies (France)',
    Region: 'Antarctica',
  },
  {
    Code: 'nc',
    Name: 'New Caledonia',
    Category: 'Dependencies (France)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'tb',
    Name: 'Saint Barthelemy',
    Category: 'Dependencies (France)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'rn',
    Name: 'Saint Martin',
    Category: 'Dependencies (France)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'sb',
    Name: 'Saint Pierre and Miquelon',
    Category: 'Dependencies (France)',
    Region: 'North America',
  },
  {
    Code: 'wf',
    Name: 'Wallis and Futuna',
    Category: 'Dependencies (France)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'aa',
    Name: 'Aruba',
    Category: 'Dependencies (Netherlands)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'uc',
    Name: 'Curacao',
    Category: 'Dependencies (Netherlands)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'nn',
    Name: 'Sint Maarten',
    Category: 'Dependencies (Netherlands)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'cw',
    Name: 'Cook Islands',
    Category: 'Dependencies (New Zealand)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'ne',
    Name: 'Niue',
    Category: 'Dependencies (New Zealand)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'tl',
    Name: 'Tokelau',
    Category: 'Dependencies (New Zealand)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'bv',
    Name: 'Bouvet Island',
    Category: 'Dependencies (Norway)',
    Region: 'Antarctica',
  },
  {
    Code: 'jn',
    Name: 'Jan Mayen',
    Category: 'Dependencies (Norway)',
    Region: 'Europe',
  },
  {
    Code: 'sv',
    Name: 'Svalbard',
    Category: 'Dependencies (Norway)',
    Region: 'Europe',
  },
  {
    Code: 'ax',
    Name: 'Akrotiri',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'av',
    Name: 'Anguilla',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'bd',
    Name: 'Bermuda',
    Category: 'Dependencies (United Kingdom)',
    Region: 'North America',
  },
  {
    Code: 'io',
    Name: 'British Indian Ocean Territory',
    Category: 'Dependencies (United Kingdom)',
    Region: 'South Asia',
  },
  {
    Code: 'vi',
    Name: 'British Virgin Islands',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'cj',
    Name: 'Cayman Islands',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'dx',
    Name: 'Dhekelia',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'fk',
    Name: 'Falkland Islands (Islas Malvinas)',
    Category: 'Dependencies (United Kingdom)',
    Region: 'South America',
  },
  {
    Code: 'gi',
    Name: 'Gibraltar',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'gk',
    Name: 'Guernsey',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'je',
    Name: 'Jersey',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'im',
    Name: 'Isle of Man',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Europe',
  },
  {
    Code: 'mh',
    Name: 'Montserrat',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'pc',
    Name: 'Pitcairn Islands',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'sh',
    Name: 'Saint Helena, Ascension, and Tristan da Cunha',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Africa',
  },
  {
    Code: 'sx',
    Name: 'South Georgia and South Sandwich Islands',
    Category: 'Dependencies (United Kingdom)',
    Region: 'South America',
  },
  {
    Code: 'tk',
    Name: 'Turks and Caicos Islands',
    Category: 'Dependencies (United Kingdom)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'aq',
    Name: 'American Samoa',
    Category: 'Dependencies (United States)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'gq',
    Name: 'Guam',
    Category: 'Dependencies (United States)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'bq',
    Name: 'Navassa Island',
    Category: 'Dependencies (United States)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'cq',
    Name: 'Northern Mariana Islands',
    Category: 'Dependencies (United States)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'rq',
    Name: 'Puerto Rico',
    Category: 'Dependencies (United States)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'vq',
    Name: 'Virgin Islands',
    Category: 'Dependencies (United States)',
    Region: 'Central America and Caribbean',
  },
  {
    Code: 'wq',
    Name: 'Wake Island',
    Category: 'Dependencies (United States)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'um',
    Name: 'United States Pacific Island Wildlife Refuges',
    Category: 'Dependencies (United States)',
    Region: 'Australia-Oceania',
  },
  {
    Code: 'ay',
    Name: 'Antarctica',
    Category: 'Miscellaneous',
    Region: 'Antarctica',
  },
  {
    Code: 'gz',
    Name: 'Gaza Strip',
    Category: 'Miscellaneous',
    Region: 'Middle East',
  },
  {
    Code: 'pf',
    Name: 'Paracel Islands',
    Category: 'Miscellaneous',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'pg',
    Name: 'Spratly Islands',
    Category: 'Miscellaneous',
    Region: 'East & Southeast Asia',
  },
  {
    Code: 'we',
    Name: 'West Bank',
    Category: 'Miscellaneous',
    Region: 'Middle East',
  },
];
